SELECT T.TABLE_SCHEMA AS table_schema, 
       T.TABLE_NAME AS table_name, 
       C.COLUMN_NAME AS column_name, 
       C.ORDINAL_POSITION AS ordinal_position
  FROM INFORMATION_SCHEMA.TABLES T
       JOIN INFORMATION_SCHEMA.COLUMNS C
         ON C.TABLE_SCHEMA = T.TABLE_SCHEMA
        AND C.TABLE_NAME = T.TABLE_NAME
 WHERE T.TABLE_TYPE = 'Base Table'
ORDER BY T.TABLE_SCHEMA,
         T.TABLE_NAME,
         C.ORDINAL_POSITION